AWSTemplateFormatVersion: 2010-09-09
Description: Step Functions for Spoptimize
Transform: AWS::Serverless-2016-10-31

Parameters:
  StackBasename:
    Description: Base name of Spoptimize stacks
    Type: String
    Default: spoptimize
  SnsTopicName:
    Description: Name of SNS topic that publishes autoscaling launch notifications
    Type: String
    Default: spoptimize-init
  DebugLambdas:
    Description: Enable debug logging of lambda functions
    Type: String
    Default: "false"
    AllowedValues: ["false", "true"]
  MaximumIterationCount:
    Description: Maximum number of iterations
    Type: Number
    Default: 48

Globals:
  Function:
    Runtime: python2.7
    Timeout: 30
    Handler: handler.handler
    MemorySize: 1024
    Environment:
      Variables:
        SPOPTIMIZE_DEBUG: !Ref DebugLambdas

Resources:
  StartStateMachineFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-start-state-machine"
      Description: Processes autoscaling launch notifications via SNS and starts Spoptimize Step Functions
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackBasename}-iam-global-lambda-role"
      CodeUri: ./target/lambda-pkg.zip
      Environment:
        Variables:
          SPOPTIMIZE_ACTION: 'start-state-machine'
          SPOPTIMIZE_SFN_ARN: !Ref SpotRequestor
      Events:
        AsgLaunchNotifications:
          Type: SNS
          Properties:
            Topic: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${SnsTopicName}"

  TestNewAsgInstanceFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ondemand-instance-healthy"
      Description: Checks health and status of launched autoscaling instance
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackBasename}-iam-global-lambda-role"
      CodeUri: ./target/lambda-pkg.zip
      Environment:
        Variables:
          SPOPTIMIZE_ACTION: 'ondemand-instance-healthy'

  IncrementCountFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-increment-count"
      Description: Increment iteration counter
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackBasename}-iam-global-lambda-role"
      CodeUri: ./target/lambda-pkg.zip
      Environment:
        Variables:
          SPOPTIMIZE_ACTION: 'increment-count'

  RequestSpotInstanceFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-request-spot"
      Description: Requests a spot instance to replace launched autoscaling instance
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackBasename}-iam-global-lambda-role"
      CodeUri: ./target/lambda-pkg.zip
      Environment:
        Variables:
          SPOPTIMIZE_ACTION: 'request-spot'

  CheckSpotRequestFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-check-spot"
      Description: Checks the status of spot instance request
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackBasename}-iam-global-lambda-role"
      CodeUri: ./target/lambda-pkg.zip
      Environment:
        Variables:
          SPOPTIMIZE_ACTION: 'check-spot'

  AutoScalingGroupDisappearedFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-term-spot-instance"
      Description: Terminates spot instance (if online) after autoscaling group disappears
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackBasename}-iam-global-lambda-role"
      CodeUri: ./target/lambda-pkg.zip
      Environment:
        Variables:
          SPOPTIMIZE_ACTION: 'term-spot-instance'

  AttachSpotBeforeTermOnDemandFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-attach-spot"
      Description: Attaches spot instance to autoscaling group
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackBasename}-iam-global-lambda-role"
      CodeUri: ./target/lambda-pkg.zip
      Environment:
        Variables:
          SPOPTIMIZE_ACTION: 'attach-spot'

  TestAttachedInstance:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-spot-instance-healthy"
      Description: Checks health and status of attached spot instance
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackBasename}-iam-global-lambda-role"
      CodeUri: ./target/lambda-pkg.zip
      Environment:
        Variables:
          SPOPTIMIZE_ACTION: 'spot-instance-healthy'

  SpotRequestor:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${AWS::StackName}-spot-requestor"
      RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackBasename}-iam-global-state-machine"
      DefinitionString:
        Fn::Sub: |-
          {
            "Comment": "Spoptimize State Machine",
            "StartAt": "Wait for New ASG Instance",
            "States": {
              "Wait for New ASG Instance": {
                "Type": "Wait",
                "SecondsPath": "$.init_sleep_interval",
                "Next": "Test New ASG Instance"
              },
              "Test New ASG Instance": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackBasename}-ondemand-instance-healthy",
                "Next": "OD Instance Healthy?",
                "ResultPath": "$.ondemand_instance_status",
                "Retry": [{
                  "ErrorEquals": [ "States.ALL" ],
                  "IntervalSeconds": 5,
                  "MaxAttempts": 5,
                  "BackoffRate": 2.5
                }]
              },
              "OD Instance Healthy?": {
                "Type": "Choice",
                "Choices": [{
                  "Variable": "$.ondemand_instance_status",
                  "StringEquals": "Healthy",
                  "Next": "Request Spot Instance"
                },{
                  "Variable": "$.ondemand_instance_status",
                  "StringEquals": "Terminated",
                  "Next": "No Op"
                },{
                  "Variable": "$.ondemand_instance_status",
                  "StringEquals": "Protected",
                  "Next": "No Op"
                },{
                  "Variable": "$.ondemand_instance_status",
                  "StringEquals": "AutoScaling Group Disappeared",
                  "Next": "No Op"
                }],
                "Default": "Wait for New ASG Instance"
              },
              "No Op": {
                "Type": "Succeed"
              },
              "Request Spot Instance": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackBasename}-request-spot",
                "ResultPath": "$.spot_request",
                "Next": "Wait For Spot Request",
                "Retry": [{
                  "ErrorEquals": [ "States.ALL" ],
                  "IntervalSeconds": 5,
                  "MaxAttempts": 5,
                  "BackoffRate": 2.5
                }]
              },
              "Wait For Spot Request": {
                "Type": "Wait",
                "SecondsPath": "$.spot_req_sleep_interval",
                "Next": "Check Spot Request"
              },
              "Check Spot Request": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackBasename}-check-spot",
                "Next": "Spot Request Status?",
                "ResultPath": "$.spot_request_result",
                "Retry": [{
                  "ErrorEquals": [ "States.ALL" ],
                  "IntervalSeconds": 5,
                  "MaxAttempts": 5,
                  "BackoffRate": 2.5
                }]
              },
              "Spot Request Status?": {
                "Type": "Choice",
                "Choices": [{
                  "Variable": "$.spot_request_result",
                  "StringEquals": "Pending",
                  "Next": "Wait For Spot Request"
                },{
                  "Variable": "$.spot_request_result",
                  "StringEquals": "Failure",
                  "Next": "Increment Failure Count"
                }],
                "Default": "Attach Spot Instance"
              },
              "Increment Failure Count": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackBasename}-increment-count",
                "Next": "Check Iteration Count?",
                "ResultPath": "$.iteration_count",
                "Retry": [{
                  "ErrorEquals": [ "States.ALL" ],
                  "IntervalSeconds": 1,
                  "MaxAttempts": 5
                }]
              },
              "Check Iteration Count?": {
                "Type": "Choice",
                "Choices": [{
                  "Variable": "$.iteration_count",
                  "NumericLessThanEquals": ${MaximumIterationCount},
                  "Next": "Sleep after Failed Spot Request"
                }],
                "Default": "Execution Exhaustion"
              },
              "Execution Exhaustion": {
                "Type": "Fail"
              },
              "Sleep after Failed Spot Request": {
                "Type": "Wait",
                "SecondsPath": "$.spot_failure_sleep_interval",
                "Next": "Test New ASG Instance"
              },
              "Terminate Spot": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackBasename}-term-spot-instance",
                "End": true,
                "Retry": [{
                  "ErrorEquals": [ "States.ALL" ],
                  "IntervalSeconds": 5,
                  "MaxAttempts": 5,
                  "BackoffRate": 2.5
                }]
              },
              "Attach Spot Instance": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackBasename}-attach-spot",
                "ResultPath": "$.spot_attach_result",
                "Next": "Check Attachment?",
                "Retry": [{
                  "ErrorEquals": [ "States.ALL" ],
                  "IntervalSeconds": 5,
                  "MaxAttempts": 5,
                  "BackoffRate": 2.5
                }]
              },
              "Check Attachment?": {
                "Type": "Choice",
                "Choices": [{
                  "Variable": "$.spot_attach_result",
                  "StringEquals": "AutoScaling Group Disappeared",
                  "Next": "Terminate Spot"
                },{
                  "Variable": "$.spot_attach_result",
                  "StringEquals": "Spot Instance Disappeared",
                  "Next": "Increment Failure Count"
                },{
                  "Variable": "$.spot_attach_result",
                  "StringEquals": "OD Instance Disappeared Or Protected",
                  "Next": "Terminate Spot"
                },{
                  "Variable": "$.spot_attach_result",
                  "StringEquals": "AutoScaling group not sized correctly",
                  "Next": "Terminate Spot"
                },{
                  "Variable": "$.spot_attach_result",
                  "StringEquals": "Instance missing",
                  "Next": "Increment Failure Count"
                },{
                  "Variable": "$.spot_attach_result",
                  "StringEquals": "Invalid instance",
                  "Next": "Increment Failure Count"
                }],
                "Default": "Wait for Attachment"
              },
              "Wait for Attachment": {
                "Type": "Wait",
                "SecondsPath": "$.spot_attach_sleep_interval",
                "Next": "Test Attached Instance"
              },
              "Test Attached Instance": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackBasename}-spot-instance-healthy",
                "Next": "Spot Instance Healthy?",
                "ResultPath": "$.spot_instance_status",
                "Retry": [{
                  "ErrorEquals": [ "States.ALL" ],
                  "IntervalSeconds": 5,
                  "MaxAttempts": 5,
                  "BackoffRate": 2.5
                }]
              },
              "Spot Instance Healthy?": {
                "Type": "Choice",
                "Choices": [{
                  "Variable": "$.spot_instance_status",
                  "StringEquals": "Healthy",
                  "Next": "Success"
                },{
                  "Variable": "$.spot_instance_status",
                  "StringEquals": "Terminated",
                  "Next": "Spot Instance Failure"
                },{
                  "Variable": "$.spot_instance_status",
                  "StringEquals": "AutoScaling Group Disappeared",
                  "Next": "Terminate Spot"
                }],
                "Default": "Wait for Attachment"
              },
              "Spot Instance Failure": {
                "Type": "Fail"
              },
              "Success": {
                "Type": "Succeed"
              }
            }
          }

Outputs:
  SpotRequestorArn:
    Description: Arn of Spot Requestor State Machine
    Value: !Ref SpotRequestor
  SpotRequestorName:
    Description: Name of Spot Requestor State Machine
    Value: !GetAtt SpotRequestor.Name
